name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
      env:
        REGISTRY: ghcr.io
